### ISSUE TITLE
An error occurs when we want create a user

### ISSUE THREAD

**Issue by 74nu5** [wihary/dotnet.JsonIdentityProvider#1]
When creating a user, the API returns a code 400 (Bad Request).

url : https://localhost:5001/api/user
body : 
```json
{
	"Name": "test",
	"Password": "test",
	"Claims": ["SuperUser:True"]
}
```

This is because the claims are not stored in a json file.

**Comment by wihary** [comment]
Indeed claims store is still WIP :)

**Comment by 74nu5** [comment]
Ok, I have done this on my pull request #2
